/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as WorksIndexRouteImport } from './routes/works/index'
import { Route as WorksSlugRouteImport } from './routes/works/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/works/$slug',
  path: '/works/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works': typeof WorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/works/$slug' | '/works/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/works/$slug' | '/works'
  id: '__root__' | '/' | '/admin' | '/works/$slug' | '/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  WorksSlugRoute: typeof WorksSlugRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/works/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  WorksSlugRoute: WorksSlugRoute,
  WorksIndexRoute: WorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
